/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import { useKTX2Texture } from "../utils/ktxLoader";

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/scene_2.glb");

  const scene_2 = useKTX2Texture("/textures/scene_2.ktx2");

  const oceanOne = useRef();
  const oceanTwo = useRef();
  const oceanThree = useRef();
  const dolphinRef = useRef();

  useFrame((state) => {
    const t = state.clock.elapsedTime;

    // Oceans
    oceanOne.current.position.y = 0.24 * Math.sin(t + Math.PI / 4) + 1;
    oceanTwo.current.position.y = 0.2 * Math.sin(t) + 1.4;
    oceanThree.current.position.y = 0.2 * Math.sin(t + Math.PI / 3) + 1.8;

    dolphinRef.current.position.y = 1.5 * Math.sin(t * 2 + Math.PI / 3) + 2.3;
    dolphinRef.current.rotation.y = 1.5 * Math.sin(t * 2);
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane007.geometry}
        material={scene_2}
        position={[5.418, 5.164, -2.296]}
        rotation={[Math.PI / 2, -0.064, 0]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={scene_2}
        position={[0.526, 4.236, -2.334]}
        rotation={[Math.PI / 2, 0.023, 0]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={scene_2}
        position={[2.426, 3.171, -2.186]}
        rotation={[Math.PI / 2, 0.125, 0]}
      />
      <mesh
        ref={oceanOne}
        geometry={nodes.Ocean_Water.geometry}
        material={scene_2}
        position={[-0.385, 1.089, -1.457]}
        rotation={[Math.PI / 2, 0.037, 0]}
      />
      <mesh
        ref={oceanTwo}
        geometry={nodes.Ocean_Water.geometry}
        material={scene_2}
        position={[2.8, 1.589, -1.457]}
        rotation={[Math.PI / 2, 0.037, 0]}
      />
      <mesh
        ref={oceanThree}
        geometry={nodes.Ocean_Water.geometry}
        material={scene_2}
        position={[5.9, 2.089, -1.457]}
        rotation={[Math.PI / 2, 0.037, 0]}
      />
      <mesh
        ref={dolphinRef}
        geometry={nodes.Dolphin.geometry}
        material={scene_2}
        position={[5.608, 2.146, -1.252]}
        rotation={[Math.PI / 2, -0.136, 0]}
        scale={0.717}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={scene_2}
        position={[3.313, 2.244, -2.137]}
        rotation={[Math.PI / 2, -0.124, 0]}
      />
      <mesh
        geometry={nodes.Treasure_Chest_Top.geometry}
        material={scene_2}
        position={[3.33, 2.519, -2.126]}
        rotation={[Math.PI / 2, -0.124, 0]}
      />
      <mesh
        geometry={nodes.Lock.geometry}
        material={scene_2}
        position={[3.193, 2.28, -2.122]}
        rotation={[Math.PI / 2, -0.124, 0]}
      />
      <mesh
        geometry={nodes.Plane045.geometry}
        material={scene_2}
        position={[-0.387, 1.016, -0.262]}
        rotation={[0, 0, 0.144]}
      />
      <mesh
        geometry={nodes.Plane049.geometry}
        material={scene_2}
        position={[-20.599, 4.634, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Plane058.geometry}
        material={scene_2}
        position={[-20.599, 4.634, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/scene_2.glb");
