/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useKTX2Texture } from "../utils/ktxLoader";
import { SHIFT_X_AMOUNT } from "../components/curve";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/models/single_sheet.glb");

  const singlesheet = useKTX2Texture("/textures/single_sheet.ktx2");

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[28.345 - SHIFT_X_AMOUNT, 4.634, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[35.245 - SHIFT_X_AMOUNT, 4.634, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[28.345 - SHIFT_X_AMOUNT, -3.42, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[28.345 - SHIFT_X_AMOUNT - 6.9, -3.42, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[35.245 - SHIFT_X_AMOUNT, -3.42, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />

      <mesh
        geometry={nodes.Single_Sheet_Baked.geometry}
        material={singlesheet}
        position={[35.245 - SHIFT_X_AMOUNT + 6.9, -3.42, -2.755]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/single_sheet.glb");
